---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-router
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-router
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    resources:
      - namespaces
      - pods
      - services
      - nodes
      - endpoints
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - extensions
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-router
subjects:
- kind: ServiceAccount
  name: kube-router
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-router
    tier: node
  name: kube-router
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-router
      tier: node
  template:
    metadata:
      labels:
        k8s-app: kube-router
        tier: node
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: kube-router
      serviceAccount: kube-router
      containers:
      - name: kube-router
        image: docker.io/cloudnativelabs/kube-router
        imagePullPolicy: IfNotPresent
        args:
        - "--run-router=true"
        - "--run-firewall=false"
        - "--run-service-proxy=false"
        # 平滑重启BGP路由(默认true)
        - "--bgp-graceful-restart=true"
        # 从Pod到集群外部通信走SANT(默认true)
        - "--enable-pod-egress=false"
        # 启用CNI插件。 如果要与另一个CNI插件一起使用kube-router功能，请禁用（默认true）
        - "--enable-cni=false"
        ##########################################################
        #       """以上选项在配置Cilium时必须设置的参数"""
        ###########################################################
        #
        # 启用与具有相同ASN的节点的对等，如果禁用将仅与外部BGP对等体对等（默认为true
        - "--enable-ibgp=false"
        # enable ip in ip(默认true)
        - "--enable-overlay=false"
        # 将服务的群集IP添加到RIB，以便将其发布给Peer BGP
        #- "--advertise-cluster-ip=true"
        # 将外部服务IP添加到RIB，以便将其发布给Peer BGP
        #- "--advertise-external-ip=true"
        #- "--advertise-loadbalancer-ip=true"
        - "--metrics-port=20245"
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "apiserver.cluster.local"
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /healthz
            port: 20244
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 1
            memory: 1024Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: xtables-lock
          mountPath: /run/xtables.lock
          readOnly: false
        - mountPath: /etc/localtime
          name: localtime
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
