---
apiVersion: v1
kind: Service
metadata:
  name: fortio
spec:
  selector:
    app: fortio
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http-fortio
    port: 8080
    targetPort: 8080
  - name: grpc-ping
    port: 8079
    targetPort: 8079
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio
  labels:
    app: fortio
    version: v1
spec:
  selector:
    matchLabels:
      app: fortio
      version: v1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  # 最短就绪时间,只有超出这个时间 Pod 才被视为可用, 默认 0
  minReadySeconds: 2
  # 等待 deployment 创建时间
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: fortio
        version: v1
      annotations:
        # This annotation causes Envoy to serve cluster.outbound statistics via 15000/stats
        # in addition to the stats normally served by Istio.  The Circuit Breaking example task
        # gives an example of inspecting Envoy stats.
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grpc
    spec:
      containers:
      - name: fortio
        image: fortio/fortio:latest_release
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8079
          initialDelaySeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8079
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        # lifecycle:
        #   postStart:
        #     exec:
        #       command:
        #       - "/bin/sh"
        #       - "-c"
        #       - sleep 0.1
        #   preStop:
        #     exec:
        #       command:
        #       - "/bin/sh"
        #       - "-c"
        #       - sleep 3
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort:  8080
          name: http-fortio
        - containerPort:  8079
          name: grpc-ping
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
