---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  selector:
    app: httpbin
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http-app
    port: 80
    targetPort: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  httpbin-v1
  labels:
    app: httpbin
    version: v1
spec:
  selector:
    matchLabels:
      app: httpbin
      version: v1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  # 最短就绪时间,只有超出这个时间 Pod 才被视为可用, 默认 0
  minReadySeconds: 2
  # 等待 deployment 创建时间
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        lifecycle:
          postStart:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - sleep 0.1
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - sleep 3
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 80
          name: app
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
