---
apiVersion: v1
kind: Service
metadata:
  name: details
spec:
  selector:
    app: details
  type: ClusterIP
  # type: NodePort
  sessionAffinity: None
  ports:
  - name: http-app
    port: 9080
    targetPort: 9080
    nodePort: 30001
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: details
#   labels:
#     app: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  annotations:
    # 自定义 Envoy 优雅终止时长,默认 5s
    proxy.istio.io/config: |
      terminationDrainDuration: 10s
  labels:
    app: details
    version: v1
spec:
  selector:
    matchLabels:
      app: details
      version: v1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  # 最短就绪时间,只有超出这个时间 Pod 才被视为可用, 默认 0
  minReadySeconds: 2
  # 等待 deployment 创建时间
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      # serviceAccountName: details
      # 自定义 pod 强杀时间，默认 30s
      terminationGracePeriodSeconds: 30
      containers:
      - name: details
        image: docker.io/istio/examples-bookinfo-details-v1:1.16.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 9080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        lifecycle:
          postStart:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - sleep 0.1
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - sleep 3
        ports:
        - name: app
          containerPort: 9080
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        securityContext:
          runAsUser: 1000
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
