---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
spec:
  selector:
    app: productpage
  type: ClusterIP
  # type: NodePort
  sessionAffinity: None
  ports:
  - name: http-app
    port: 9080
    targetPort: 9080
    nodePort: 30002
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: productpage
#   labels:
#     app: productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  productpage
  annotations:
    # 自定义 Envoy 优雅终止时长,默认 5s
    proxy.istio.io/config: |
      terminationDrainDuration: 10s
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  productpage
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  # 最短就绪时间,只有超出这个时间 Pod 才被视为可用, 默认 0
  minReadySeconds: 2
  # 等待 deployment 创建时间
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app:  productpage
        version: v1
    spec:
      # serviceAccountName: productpage
      # 自定义 pod 强杀时间，默认 30s
      terminationGracePeriodSeconds: 30
      containers:
      - name: productpage
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.3
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - name: app
          containerPort: 9080
        resources:
          limits:
            cpu: "1"
            memory: 512M
          requests:
            cpu: "50m"
            memory: "128M"
        livenessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 10
          timeoutSeconds: 10
        lifecycle:
          postStart:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - sleep 0.1
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - sleep 3
        volumeMounts:
        - name: data
          mountPath: /data
        securityContext:
          runAsUser: 1000
      volumes:
        - name: data
          emptyDir: {}
