---
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: sample-data
  labels:
    app: sample
spec:
  replicas: 3
  ## 控制器会优先删除这些 Pod
  # scaleStrategy:
  #   podsToDelete:
  #   - sample-data-8h447
  #   - sample-data-2mmbj
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: data-vol
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: data-vol
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  selector:
    app: sample
  type: NodePort
  sessionAffinity: None
  ports:
  - name: sample
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
