apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - base

images:
  - name: gcr.io/k8s-staging-metrics-server/metrics-server
    newName: k8s.gcr.io/metrics-server/metrics-server
    newTag: v0.5.0

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: metrics-server
    namespace: kube-system
  path: patch/metrics-server.yaml

patchesStrategicMerge:
  - patch/autoscale.yaml
