---
# redis 密码
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
data:
  password: "{{ .Values.redisPassword | b64enc }}"
type: Opaque
