---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "redis-cluster.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: gossip
      port: 16379
      targetPort: 16379
  publishNotReadyAddresses: true
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-0" (include "redis-cluster.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: {{ .Values.redisNodePort.node1 }}
    - name: gossip
      port: 16379
      targetPort: 16379
      nodePort: {{ .Values.redisNodePort.gossip1 }}
  publishNotReadyAddresses: true
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ printf "%s-0" (include "redis-cluster.fullname" .) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-1" (include "redis-cluster.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: {{ .Values.redisNodePort.node2 }}
    - name: gossip
      port: 16379
      targetPort: 16379
      nodePort: {{ .Values.redisNodePort.gossip2 }}
  publishNotReadyAddresses: true
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ printf "%s-1" (include "redis-cluster.fullname" .) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-2" (include "redis-cluster.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: {{ .Values.redisNodePort.node3 }}
    - name: gossip
      port: 16379
      targetPort: 16379
      nodePort: {{ .Values.redisNodePort.gossip3 }}
  publishNotReadyAddresses: true
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ printf "%s-2" (include "redis-cluster.fullname" .) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-3" (include "redis-cluster.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: {{ .Values.redisNodePort.node4 }}
    - name: gossip
      port: 16379
      targetPort: 16379
      nodePort: {{ .Values.redisNodePort.gossip4 }}
  publishNotReadyAddresses: true
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ printf "%s-3" (include "redis-cluster.fullname" .) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-4" (include "redis-cluster.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: {{ .Values.redisNodePort.node5 }}
    - name: gossip
      port: 16379
      targetPort: 16379
      nodePort: {{ .Values.redisNodePort.gossip5 }}
  publishNotReadyAddresses: true
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ printf "%s-4" (include "redis-cluster.fullname" .) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-5" (include "redis-cluster.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: {{ .Values.redisNodePort.node6 }}
    - name: gossip
      port: 16379
      targetPort: 16379
      nodePort: {{ .Values.redisNodePort.gossip6 }}
  publishNotReadyAddresses: true
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ printf "%s-5" (include "redis-cluster.fullname" .) }}
